---
- hosts: amazonweb
  tasks:

    - name: 'download java'
      yum: name=java-1.8.0 state=latest
      tags:
        - 'tag1'

    - name: 'download tar file'
      get_url:
        url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.59/bin/apache-tomca                                                                            t-8.5.59.tar.gz
        dest: /opt
      tags:
        - 'tag2'

    - name: 'untar file'
      unarchive:
        src: /opt/apache-tomcat-8.5.59.tar.gz
        dest: /opt
        remote_src: yes
      tags:
        - 'tag3'

    - name: 'startup tomcat'
      command: nohup /opt/apache-tomcat-8.5.59/bin/startup.sh
      tags:
        - 'tag4'

    - name: 'remove tar file'
      command: rm -rf /opt/apache-tomcat-8.5.59.tar.gz
      tags:
        - 'tag5'
